### ISSUE TITLE
Tighte header for trener

### ISSUE THREAD

**Issue by jaaberg** [iterate/flowzone#12]
Jeg foreslår at vi bruker FlowZone som header for trener og tighter litt opp. Header for trener tar ca 1/3 av skjermen nå. 

Jeg foreslår også at Atleter/Aktivitet(0) holder seg sticky på toppen når man scroller nedover som trener. 

Nå: 
<img width="525" alt="screen shot 2017-01-31 at 13 34 45" src="https://cloud.githubusercontent.com/assets/1413255/22465049/203ed140-e7ba-11e6-806e-a40d93ff2038.png">
Forslag: 
<img width="570" alt="screen shot 2017-01-31 at 13 28 54" src="https://cloud.githubusercontent.com/assets/1413255/22465048/203e6ae8-e7ba-11e6-9d69-7858e4afb496.png">

**Comment by andnorda** [comment]
Hva tenker du @juliabaulin ? Hadde du laget noen skisser på dette allerede?

**Comment by juliabaulin** [comment]
siden til atletene har fått en liten FlowZone header. Ingrid sin versjon er work in progress, kan ta det neste uke.
![img_2823](https://cloud.githubusercontent.com/assets/20025575/22468697/99e6be22-e7c9-11e6-8cdf-fce60fa62e29.PNG)

**Comment by andnorda** [comment]
Fixed?
