### ISSUE TITLE
Innsendt test

### ISSUE THREAD

**Issue by magnli10** [iterate/flowzone#21]
Får ingen bekreftelse på innsendt "Test" og ingen oversikt over hva jeg har sendt inn.

**Comment by jaaberg** [comment]
Dette er en bug. Det har noe med de siste PRene igår å gjøre, kan være min der jeg rotet rundt med Dates. https://github.com/iterate/flowzone/pull/16/files

**Comment by andnorda** [comment]
Martine rapporterte også denne buggen. Tenker den er ganske kritisk.

**Comment by skeie** [comment]
Er denne fikset @jaaberg, @andnorda ?

**Comment by andnorda** [comment]
Trukke det. Men planen er jo uansett å fjerne test-funksjonalitet.

**Comment by andnorda** [comment]
Test-funksjonalitet fjernet.
