### ISSUE TITLE
Text overflow på workout title (sikkert andre steder også)

### ISSUE THREAD

**Issue by andnorda** [iterate/flowzone#36]

**Comment by jaaberg** [comment]
Fikk ikke gjenskapt denne, er den fremdeles reell?

**Comment by skeie** [comment]
Har du et bilde @andnorda ?

**Comment by skeie** [comment]
@andnorda ?

**Comment by andnorda** [comment]
![image](https://cloud.githubusercontent.com/assets/1894119/23936495/cd71d4ca-0952-11e7-84b9-780ab1152b90.png)
