### ISSUE TITLE
Input felt tømmes på focus

### ISSUE THREAD

**Issue by andnorda** [iterate/flowzone#37]
1. skriv noe i et input-felt
2. trykk utenfor unput-feltet
3. select input-feltet igjen
4. input feltet tømmes

**Comment by skeie** [comment]
Den fikset @jaaberg

**Comment by skeie** [comment]
Har du prøvd på master @andnorda ?

**Comment by andnorda** [comment]
Noice!

**Comment by skeie** [comment]
🖖
