### ISSUE TITLE
Å trykke på et input-felt på mobil fungerer ikke hver gang

### ISSUE THREAD

**Issue by andnorda** [iterate/flowzone#38]
Noen ganger når man selecter et text-input-felt på mobil så dukker ikke markøren opp, og all tekst man skriver dukker heller ikke opp.

**Comment by jaaberg** [comment]
Tipper det har med at vi benytter contenteditable divs. Tror vi slipper unna en del ekstra kode og bugs om vi bruker textarea og expander når man begynner å skrive i feltet.

**Comment by skeie** [comment]
Hvilket input felt var dette @andnorda ?

**Comment by andnorda** [comment]
Alle
