### ISSUE TITLE
Trener-profil

### ISSUE THREAD

**Issue by andnorda** [iterate/flowzone#39]
Det skjer noe rart når jeg er logget inn som Roger og åpner Ingrids profil: https://flowzone.app.iterate.no/users/YXnUE8guY6YtcfCViRQ7mcVOK993

![image](https://cloud.githubusercontent.com/assets/1894119/23706515/cc6fd6a6-040e-11e7-8f4d-37d982b0f828.png)

Noen som vet hva som er greia?
Hva vil vi vise?

**Comment by skeie** [comment]
Hvordan kom du inn på hennes profil? Via url?

**Comment by andnorda** [comment]
Jepp, via url

**Comment by skeie** [comment]
Jeg tenker kanskje man bare burde få lov til å se sine utøver/trener sin sider nå først.

**Comment by skeie** [comment]
Hva tenker folk om det?

**Comment by andnorda** [comment]
Altså begrense tilgang?

**Comment by skeie** [comment]
Japp ;>
