### ISSUE TITLE
404-side

### ISSUE THREAD

**Issue by andnorda** [iterate/flowzone#40]
Vi burde vise en 404-side for ting som ikke finnes:

https://flowzone.app.iterate.no/wat
https://flowzone.app.iterate.no/users/wat
https://flowzone.app.iterate.no/workouts/wat

**Comment by skeie** [comment]
Kan starte på denne.

**Comment by andnorda** [comment]
Er denne deployet til app.iterate?

**Comment by skeie** [comment]
Nop, jeg var litt kjapp på avtrekkeren med å close'n. Den er på vei ut nå.

**Comment by andnorda** [comment]
https://flowzone.app.iterate.no/workouts/wat gir fortsatt ikke 404

**Comment by skeie** [comment]
![image](https://cloud.githubusercontent.com/assets/1346122/23745246/cf3a3210-04b7-11e7-888e-e3de801a7a7b.png)

**Comment by andnorda** [comment]
![image](https://cloud.githubusercontent.com/assets/1894119/23745269/e964cae2-04b7-11e7-82e0-16d516e3aaf6.png)

**Comment by jaaberg** [comment]
Denne er vel fikset nå

**Comment by andnorda** [comment]
https://flowzone.app.iterate.no/users/wat
https://flowzone.app.iterate.no/workouts/wat

Disse lenkene redirecter til /notFound nå, og det gjør at å gå tilbake i browser-historien ikke funker som det skal. Du blir bare redirectet til /notFound igjen, og kommer det aldri tilbake.

**Comment by skeie** [comment]
Da skal disse været fikset.

**Comment by andnorda** [comment]
Nei, de to sidene redirecter fortsatt til /notFound, og det gjør at tilbake-knappen ikke fungerer som det skal. Kan vi ikke bare rendre 404-siden på den siden man kommer til, altså uten å redirecte til /notFound?

**Comment by skeie** [comment]
x attempt is the charm, right?
