### ISSUE TITLE
Epost mangler navn

### ISSUE THREAD

**Issue by andnorda** [iterate/flowzone#43]
Fikk nettopp denne eposten fra flowzone:

En ny melding fra .
Meldingen er: Svarer jeg bare ved å skrive noe her? (Litt rart å ikke
skrive svar under det jeg svarer på, men over.) Og hei, Roger! Det er
fordi jeg har glemt å legge inn øktene her. Skal synce pulsklokka mi
nå og legge det inn!.

Som dere ser mangler den navn på avsender.

**Comment by skeie** [comment]
Hvilken bruker kom den fra?

**Comment by andnorda** [comment]
Pia.

Jeg fikk nettopp en ny epost der det var navn, men det var for en kommentar på en økt. Den over er for en kommentar på profilen hennes. 

Jeg får ikke epost når hun laster opp økter, og det burde jeg kanskje?

**Comment by skeie** [comment]
Jeg har bare lagt inn at man får epost ved kommentarer. Så jeg er helt
enig, burde utvides til at man får en epost ved alle actions noens gjør
imo, så kan vi heller fjerne der vi ser at det ikke gir verdi.

Jeg kan debugge den navneløse eposten i morgen. Også kan jeg evt begynne på
å utvide epost-innsendingen.

**Comment by skeie** [comment]
Den skal være fikset. La oss åpne den igjen hvis det skjer igjen.
