### ISSUE TITLE
Går det bare an å skrive kommentar til en test?

### ISSUE THREAD

**Issue by skeie** [iterate/flowzone#5]
![image](https://cloud.githubusercontent.com/assets/1346122/22456781/de24f1b0-e794-11e6-8191-5283c80dddba.png)

**Comment by andnorda** [comment]
Julia har laget et nytt design for profilsiden til brukere som fikser denne på en bra måte. Jeg implementerer de endringene nå.

**Comment by andnorda** [comment]
Har ikke tid til å fikse designet nå, men mellomløsningen jeg har mekket er at det på andre sin profiler står: "Skriv noe til ${name}..." 

Da blir teksten mer forståelig for Ingrid, i det minste.

**Comment by andnorda** [comment]
Chat er nå separat.
