### ISSUE TITLE
Direkte-lenke i eposter

### ISSUE THREAD

**Issue by andnorda** [iterate/flowzone#52]
Kan vi ha direkte lenke til riktig skjermbilde i eposter-notifikasjoner?

**Comment by skeie** [comment]
Hva mener du?

**Comment by andnorda** [comment]
Om man får kommentar på en økt fra treneren sin, så er det lenke direkte til den økta i epost-notifikasjonen.

**Comment by skeie** [comment]
Denne skal være fikset, sender med en link til flowzone.app.iterate.no/notifications

Det var det du mente @andnorda ?

**Comment by andnorda** [comment]
Jeg tenkte at hvis man får en kommentar på en økt, f.eks /workouts/best-workout, så er lenken man får på epost: flowzone.app.iterate.no/workouts/best-workout.
