### ISSUE TITLE
Onboarding flow ny bruker

### ISSUE THREAD

**Issue by skeie** [iterate/flowzone#6]
![image](https://cloud.githubusercontent.com/assets/1346122/22456807/fcf5986a-e794-11e6-873f-99f3a72b8d73.png)

**Comment by juliabaulin** [comment]
https://www.dropbox.com/s/3vxh7wt5rofnlbf/Flowzone_ny%20%C3%B8kt.sketch?dl=0

**Comment by andnorda** [comment]
Et dumt spørsmål

**Comment by andnorda** [comment]
Til juliabaulin

**Comment by andnorda** [comment]
@juliabaulin

**Comment by andnorda** [comment]
@juliabaulin test

**Comment by juliabaulin** [comment]
Sketch filen til Onboarding ligger her: https://www.dropbox.com/s/cypkwn7bijbykx0/Flowzone_Onboarding%20ny%20bruker.sketch?dl=0

**Comment by andnorda** [comment]
Fixed
